format: 1
mpc:
  defaults:
    group: Libraries
    overlay: base 
    relstage: stable
    configure_args:
      - --disable-shared
      - --with-pic
      - --with-gmp=${GMP_PREFIX}
      - --with-mpfr=${MPFR_PREFIX}
    docfiles: []
    urls:
      - url: http://ftp.gnu.org/gnu/${P}/${P}-${V_PKG}.tar.gz

  shasums:
    mpc-1.3.1.tar.gz: ab642492f5cf882b74aa0cb730cd410a81edcdbec895183ce930e706c1c759b8
    mpc-1.2.1.tar.gz: 17503d2c395dfcf106b622dc142683c1199431d095367c6aacba6eec30340459
    mpc-1.1.0.tar.gz: 6985c538143c1208dcb1ac42cedad6ff52e267b47e5f970183a3e75125b43c2e
    mpc-1.0.3.tar.gz: 617decc6ea09889fb08ede330917a00b16809b8db88c29c31bfbb49cbf88ecc3
    mpc-1.0.2.tar.gz: b561f54d8a479cee3bc891ee52735f18ff86712ba30f036f8b8537bae380c488
    mpc-1.0.1.tar.gz: ed5a815cfea525dc778df0cb37468b9c1b554aaf30d9328b1431ca705b7400ff

  versions:
    1.2.1;1.3.1-1:
      config:
        build_requires: [gmp/6.3.0, mpfr/4.2.1]
    1.0.{2,3};1.0.3-2;1.1.0-{1..4};1.3.1:
      config:
        relstage: deprecated

