---
# yamllint disable rule:line-length
format: 1
parmetis:
  defaults:
    group: MPI
    overlay: base
    relstage: stable
    systems: [merlin-*, ra-*]
    docfiles: [Changelog, Install.txt, LICENSE.txt]
    urls:
      - url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/$P/$P-${V_PKG}.tar.gz 
        name: $P-${V_PKG}.tar.gz

  shasums:
    - parmetis-4.0.3.tar.gz: f2d9a231b7cf97f1fee6e8c9663113ebf6c240d407d3c118c55b3633d6be6e5f

  versions:
    4.0.3_slurm:
      variants:
        - group_deps:
            compiler:
              gcc: [9.5.0, 10.4.0, 11.4.0, 12.3.0, 13.1.0]
            mpi:
              openmpi: [4.1.5_slurm]
          build_requires: [cmake/3.20.5]

