format: 1
patchelf:
  defaults:
    group: System
    overlay: base
    relstage: stable
    urls:
      - url: https://github.com/NixOS/$P/archive/$V.tar.gz
        name: $P-$V.tar.gz
  shasums:
    patchelf-0.8.1.tar.bz2: 12367e9ce9c315a26e14f11db8542e2e0f3a877aff52590912111268cb775bef7ce713368eb3759df6823f457a7b6d0419fd02c231d40db5dd0b853f41caf254
    patchelf-0.11.tar.gz: b156bad513d5bac33aaf61d5f04d5a78efc81abf8c0ccb851f605e1137c21e671b4933263a47543daf5064db5e83c9afa836b1aea143fca7d8e6a18ebf96beb8
    patchelf-0.12.tar.gz: 2563a5b22b90392d5755d9a08022daf8570fa1b741becbbca92548d0a2f82f7ee21175a2c34816a4653c89c2219bf59b1440304b0fa2d49842e398ab18b9923c
    patchelf-0.14.5.tar.gz: ca6ef65d53842a0e38f43aeb0a476a537c29c8528a5f613bb1ef16e08f6756d9
    patchelf-0.18.0.tar.gz: 1451d01ee3a21100340aed867d0b799f46f0b1749680028d38c3f5d0128fb8a7

  versions:
    0.8.1;0.11;0.12;0.14.5:
    0.18.0:
      config:
        build_requires: [gcc/12.3.0]

