---
format: 1
curl:
  defaults:
    group: Tools
    overlay: base
    relstage: stable
    configure_args:
      - --with-openssl
    docfiles: []
    urls:
      - url: https://curl.se/download/$P-${V_PKG}.tar.gz
  shasums:

  versions:
    8.13.0:
      config:
        build_requires: [libpsl/0.21.5, openssl/3.4.1]
    8.11.0:
      config:
        build_requires: [libpsl/0.21.5, openssl/1.1.1w]
