format: 1
shs-libcxi:
  defaults:
    group: Libraries
    compile_in_sourcetree: true
    relstage: unstable
    urls:
      - url: https://github.com/HewlettPackard/shs-libcxi/archive/refs/heads/main.zip
  # Requires local packages:
  #   zypper install libconfig-devel
  #   zypper install libuv-devel
  #   zypper install fuse-devel
  #   zypper install libsensors4-devel
  shasums:
  versions:
    12.0.1:
      config:
        relstage: stable
        urls:
          # - url: https://github.com/HewlettPackard/shs-libcxi/archive/refs/heads/main.zip
          - url: https://github.com/HewlettPackard/shs-libcxi/archive/refs/tags/release/shs-12.0.1.tar.gz
            name: shs-libcxi-12.0.1.tar.bz2
        patch_files:
          - patch/cassini_csr_defs-v12.0.1.patch
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          suffix: '-oss'
          use_overlays: [PSI]
          use_flags: [merlin7]
          build_requires: [gcc/12.3.0,shs-cassini-headers/12.0.1-oss,shs-cxi-driver/12.0.1-oss]
