format: 1
gmp:
  defaults:
    group: Libraries
    overlay: base 
    relstage: stable
    configure_args:
      - --disable-shared
      - --with-pic
      - CC=gcc
      - CPP=/usr/bin/cpp
    docfiles: []
    urls:
      - url: https://gmplib.org/download/$P/$P-$V_PKG.tar.bz2
  shasums:
    gmp-6.3.0.tar.bz2: ac28211a7cfb609bae2e2c8d6058d66c8fe96434f740cf6fe2e47b000d1c20cb
    gmp-6.2.1.tar.bz2: eae9326beb4158c386e39a356818031bd28f3124cf915f8c5b1dc4c7a36b4d7c
    gmp-6.2.0.tar.bz2: f51c99cb114deb21a60075ffb494c1a210eb9d7cb729ed042ddb7de9534451ea
    gmp-6.1.2.tar.gz: 97904147e7216a58cf5870a810aa1347488fe714d710f53d42f72247be7b77f7
    gmp-6.1.2.tar.bz2: 5275bb04f4863a13516b2f39392ac5e272f5e1bb8057b18aec1c9b79d73d8fb2
    gmp-6.1.2.tar.bz2.sig: 7de6a71ccadc8e1d761713a9fce2ef67de2dcc8cbaee51d464d360df07f5e951
    gmp-6.1.2-1.tar.gz: 97904147e7216a58cf5870a810aa1347488fe714d710f53d42f72247be7b77f7
    gmp-6.1.2-1.tar.bz2: 97904147e7216a58cf5870a810aa1347488fe714d710f53d42f72247be7b77f7
    gmp-6.1.1.tar.lz: 2ac8d815c670bbfecc2e796b9bcd4869eecd31299868248b0b221bc64a2570b2
    gmp-6.1.1.tar.bz2: a8109865f2893f1373b0a8ed5ff7429de8db696fc451b1036bd7bdf95bbeffd6
    gmp-6.1.0.tar.bz2: 498449a994efeba527885c10405993427995d3f86b8768d8cdf8d9dd7c6b73e8
    gmp-6.0.0.tar.bz2: 7f8e9a804b9c6d07164cf754207be838ece1219425d64e28cfa3e70d5c759aaf
    gmp-5.1.3.tar.bz2: 752079520b4690531171d0f4532e40f08600215feefede70b24fabdc6f1ab160
    gmp-5.1.1.tar.bz2: a0d4779f48b36519dfaceb5f987a7c76fcac223258bebea3bb2244310970afad

  versions:
    6.2.1;6.3.0:

    5.1.1;6.0.0;6.1.0;6.1.1;6.1.2;6.1.2-1;6.2.0:
      config:
        relstage: deprecated

