---
format: 1
RFdiffusion:
  defaults:
    group: EM
    overlay: base
    relstage: unstable

  versions:
    dev:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: unstable
