format: 1
cmake:
  defaults:
    overlay: base
    relstage: stable
    urls:
      - url: https://cmake.org/files/v${V_MAJOR}.${V_MINOR}/$P-$V.tar.gz

  shasums:
    cmake-2.8.12.2.tar.gz: 8c6574e9afabcb9fc66f463bb1f2f051958d86c85c37fccf067eb1a44a120e5e 
    cmake-3.1.3.tar.gz:    45f4d3fa8a2f61cc092ae461aac4cac1bab4ac6706f98274ea7f314dd315c6d0 
    cmake-3.3.2.tar.gz:    e75a178d6ebf182b048ebfe6e0657c49f0dc109779170bad7ffcb17463f2fc22
    cmake-3.4.1.tar.gz:    d41462bdd80dc37f0d5608167b354bb3af8c068eee640be04c907154c5c113e2
    cmake-3.6.3.tar.gz:    7d73ee4fae572eb2d7cd3feb48971aea903bb30a20ea5ae8b4da826d8ccad5fe
    cmake-3.8.1.tar.gz:    ce5d9161396e06501b00e52933783150a87c33080d4bdcef461b5b7fd24ac228
    cmake-3.9.6.tar.gz:    7410851a783a41b521214ad987bb534a7e4a65e059651a2514e6ebfc8f46b218
    cmake-3.10.2.tar.gz:   80d0faad4ab56de07aa21a7fc692c88c4ce6156d42b0579c6962004a70a3218b 
    cmake-3.10.3.tar.gz:   0c3a1dcf0be03e40cf4f341dda79c96ffb6c35ae35f2f911845b72dab3559cf8 
    cmake-3.13.3.tar.gz:   665f905036b1f731a2a16f83fb298b1fb9d0f98c382625d023097151ad016b25
    cmake-3.14.0.tar.gz:   aa76ba67b3c2af1946701f847073f4652af5cbd9f141f221c97af99127e75502
    cmake-3.15.5.tar.gz:   fbdd7cef15c0ced06bb13024bfda0ecc0dedbcaaaa6b8a5d368c75255243beb4
    cmake-3.19.2.tar.gz:   e3e0fd3b23b7fb13e1a856581078e0776ffa2df4e9d3164039c36d3315e0c7f0
    cmake-3.20.5.tar.gz:   12c8040ef5c6f1bc5b8868cede16bb7926c18980f59779e299ab52cbc6f15bb0
    cmake-3.23.2.tar.gz:   f316b40053466f9a416adf981efda41b160ca859e97f6a484b447ea299ff26aa
    cmake-3.25.2.tar.gz:   c026f22cb931dd532f648f087d587f07a1843c6e66a3dfca4fb0ea21944ed33c
    cmake-3.26.3.tar.gz:   bbd8d39217509d163cb544a40d6428ac666ddc83e22905d3e52c925781f0f659

  versions:
    2.8.12.2;3.1.3;3.3.2;3.4.1;3.6.3;3.9.6:
    3.8.1:
      config:
        relstage: removed
    3.10.3;3.13.3;3.14.0:
      config:
        build_requires: [gcc/7.3.0]
    3.15.5;3.19.2;3.20.5;3.23.2;3.25.2:
      config:
        build_requires: [gcc/7.3.0, patchelf/0.8.1]
    3.26.3:
      config:
        build_requires: [gcc/7.3.0, patchelf/0.8.1]
        relstage: unstable