---
format: 1
crYOLO:
  defaults:
    group: EM
    overlay: base
    relstage: stable
  versions:
    1.9.9:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: stable
          build_requires: ['cuda/11.8.0']
          runtime_deps: ['cuda/11.8.0']
