format: 1
shs-cxi-driver:
  defaults:
    group: Libraries
    compile_in_sourcetree: true
    relstage: unstable
    urls:
      - url: https://github.com/HewlettPackard/shs-cxi-driver/archive/refs/heads/main.zip
        name: shs-cxi-driver-main.tar.bz2
  shasums:
   shs-cassini-headers-12.0.1.tar.bz2: d1af6dbc79df740f56667e5b3e1501003cbbf9957f214debb5556bd7eb24167e
  versions:
    12.0.1:
      config:
        relstage: stable
        urls:
          - url: https://github.com/HewlettPackard/shs-cxi-driver/archive/refs/tags/release/shs-12.0.1.tar.gz
            name: shs-cxi-driver-12.0.1.tar.bz2
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          suffix: '-oss'
          use_overlays: [PSI]
          use_flags: [merlin7]
