---
# yamllint disable rule:line-length
format: 1
trilinos:
  defaults:
    group: HDF5
    overlay: base
    relstage: stable
    systems: [rhel7, rhel8, rhel9]
    urls:
      - url: https://github.com/trilinos/Trilinos/archive/refs/tags/$P-release-${V_MAJOR}-${V_MINOR}-${V_PATCHLVL}.tar.gz
        name: $P-${V_PKG}.tar.gz

  versions:
    14.4.0:
      variants:
        - relstage: unstable
          overlay: devel
          group_deps:
            compiler: {gcc: [10.4.0]}
            mpi: {openmpi: [4.1.5]}
            hdf5: {hdf5: [1.10.8]}
          build_requires: [cmake/3.25.2, OpenBLAS/0.3.23, parmetis/4.0.3]

    12.12.1:
      config:
        relstage: deprecated
      variants:
        - group_deps:
            compiler: {gcc: [7.3.0]}
            mpi: {openmpi: [1.10.7, 2.1.2, 3.0.0]}
            hdf5: {hdf5: [1.10.1]}
          build_requires: [hdf5/1.10.1, cmake/3.6.3, OpenBLAS/0.2.20, parmetis/4.0.3]
