---
format: 1
visit:
  defaults:
    group: Tools
    overlay: base
    relstage: stable
    systems: [sles.*, rhel.*]
    docfiles: [Copyright, NEWS, README]
    build_functions:
      configure: []
      compile: []
  versions:
    3.4.2:
      config:
        urls:
          - url: https://github.com/visit-dav/visit/releases/download/v${V_PKG}/visit-install3_4_2
            name: visit-install-${V_PKG}
            unpacker: none
          - url: https://github.com/visit-dav/visit/releases/download/v${V_PKG}/visit3_4_2.linux-x86_64-rocky8.tar.gz
            name: visit3_4_2.linux-x86_64.tar.gz
            unpacker: none
        relstage: stable

