format: 1
GAMS:
  defaults:
    group: Tools
    relstage: stable
  shasums:
  versions:
    50.3.0:
      variants:
        - relstage: stable
          overlay: base
    42.3.0:
      variants:
        - relstage: stable
          overlay: base
    31.1.1:
      variants:
        - relstage: deprecated
          overlay: base
    30.3.0:
      variants:
        - relstage: deprecated 
          overlay: base
