format: 1
GAMS:
  defaults:
    group: Tools
    relstage: stable
  shasums:
  versions:
    50.3.0:
      variants:
        - relstage: stable
          overlay: merlin
          use_overlays: [PSI]
    42.3.0:
      variants:
        - relstage: stable
          overlay: merlin
          use_overlays: [PSI]
    31.1.1:
      variants:
        - relstage: deprecated
          overlay: merlin
          use_overlays: [PSI]
    30.3.0:
      variants:
        - relstage: deprecated 
          overlay: merlin
          use_overlays: [PSI]
