---
format: 1
warp:
  defaults:
    group: EM
    overlay: base
    relstage: unstable

  versions:
    2.0.0dev33:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: unstable
