---
format: 1
xz:
  defaults:
    group: Tools
    overlay: base
    relstage: stable
    docfiles:
      - AUTHORS
      - COPYING
      - COPYING.GPLv2
      - COPYING.GPLv3
      - COPYING.LGPLv2.1
      - ChangeLog
      - NEWS
      - PACKAGERS
      - README
      - THANKS
      - TODO
    urls:
      - url: https://sourceforge.net/projects/lzmautils/files/$P-${V_PKG}.tar.gz
  shasums:
  versions:
    5.8.0:
      config:

